/* Microchip Technology Inc. and its subsidiaries.  You may use this software 
 * and any derivatives exclusively with Microchip products. 
 * 
 * THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS".  NO WARRANTIES, WHETHER 
 * EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED 
 * WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A 
 * PARTICULAR PURPOSE, OR ITS INTERACTION WITH MICROCHIP PRODUCTS, COMBINATION 
 * WITH ANY OTHER PRODUCTS, OR USE IN ANY APPLICATION. 
 *
 * IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE, 
 * INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND 
 * WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS 
 * BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE.  TO THE 
 * FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS 
 * IN ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF 
 * ANY, THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
 *
 * MICROCHIP PROVIDES THIS SOFTWARE CONDITIONALLY UPON YOUR ACCEPTANCE OF THESE 
 * TERMS. 
 */

/* 
 * File:   
 * Author: 
 * Comments:
 * Revision history: 
 */

// This is a guard condition so that contents of this file are not included
// more than once.  
#ifndef PIN_MACROS_H
#define	PIN_MACROS_H

#include <xc.h> // include processor files - each processor file is guarded.  

// PORT A
#define INPUT_CHANNEL_1_PIN                 PORTAbits.RA0
#define INPUT_CHANNEL_2_PIN                 PORTAbits.RA1
#define INPUT_CHANNEL_3_PIN                 PORTAbits.RA2
#define OUTPUT_GROUP_SELECT_1_PIN           PORTAbits.RA3
#define OUTPUT_GROUP_SELECT_2_PIN           PORTAbits.RA4
#define OUTPUT_GROUP_SELECT_3_PIN           PORTAbits.RA5
#define POS3P3_PGOOD_PIN                    PORTAbits.RA7

// PORT B
#define nOUTPUT_GROUP_2_CHANNEL_1_PIN       LATBbits.LATB0
#define nOUTPUT_GROUP_2_CHANNEL_2_PIN       LATBbits.LATB1
#define nOUTPUT_GROUP_2_CHANNEL_3_PIN       LATBbits.LATB2
#define nOUTPUT_GROUP_3_CHANNEL_1_PIN       LATBbits.LATB3
#define nOUTPUT_GROUP_3_CHANNEL_2_PIN       LATBbits.LATB4
#define nOUTPUT_GROUP_3_CHANNEL_3_PIN       LATBbits.LATB5

// PORT C
#define HEARTBEAT_LED_PIN                   LATCbits.LATC3
#define RESET_LED_PIN                       LATCbits.LATC4
#define nOUTPUT_GROUP_1_CHANNEL_1_PIN       LATCbits.LATC5
#define nOUTPUT_GROUP_1_CHANNEL_2_PIN       LATCbits.LATC6
#define nOUTPUT_GROUP_1_CHANNEL_3_PIN       LATCbits.LATC7

#endif	/* PIN_MACROS_H */

